# Generated by Django 2.0.2 on 2018-09-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alyaf_daraje2_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'alyaf_daraje2_18',
            },
        ),
        migrations.CreateModel(
            name='alyaf_jaryan_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'alyaf_jaryan_18',
            },
        ),
        migrations.CreateModel(
            name='alyaf_jaryan_30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'alyaf_jaryan_30',
            },
        ),
        migrations.CreateModel(
            name='alyaf_jaryan_36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'alyaf_jaryan_36',
            },
        ),
        migrations.CreateModel(
            name='alyaf_kham_va_rangshode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'alyaf_kham_va_rangshode',
            },
        ),
        migrations.CreateModel(
            name='bestankari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ashkhas', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='بستانکاری خاطره از اشخاص')),
                ('bank', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='بانک')),
            ],
            options={
                'db_table': 'bestankari',
            },
        ),
        migrations.CreateModel(
            name='nakh_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'nakh_18',
            },
        ),
        migrations.CreateModel(
            name='nakh_24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'nakh_24',
            },
        ),
        migrations.CreateModel(
            name='nakh_2_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'nakh_2_18',
            },
        ),
        migrations.CreateModel(
            name='nakh_30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'nakh_30',
            },
        ),
        migrations.CreateModel(
            name='nakh_36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'nakh_36',
            },
        ),
        migrations.CreateModel(
            name='zayeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(verbose_name='فی هر کیلوگرم')),
                ('val', models.FloatField(verbose_name='ارزش ریال')),
                ('timestamp', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'zayeat',
            },
        ),
    ]
