# Generated by Django 2.0.2 on 2018-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alyaf_daraje2_18_alyaf_jaryan_18_alyaf_jaryan_30_alyaf_jaryan_36_alyaf_kham_va_rangshode_bestankari_'),
    ]

    operations = [
        migrations.CreateModel(
            name='bedehkari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ashkhas', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='بدهکاری خاطره به اشخاص')),
                ('bank', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='بانک')),
            ],
            options={
                'db_table': 'bedehkari',
            },
        ),
    ]
