# Generated by Django 2.0.2 on 2018-09-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_bedehkari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(blank=True, null=True, verbose_name='مقدار(کیلوگرم)')),
                ('fi', models.FloatField(blank=True, null=True, verbose_name='فی هر کیلوگرم')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsoolName', models.CharField(max_length=100, verbose_name='مقدار(کیلوگرم)')),
            ],
            options={
                'db_table': 'mahsool',
            },
        ),
        migrations.AddField(
            model_name='amar',
            name='Mahsool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Mahsool'),
        ),
    ]
