# Generated by Django 2.0.2 on 2018-09-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180928_1035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amar',
            table='amar',
        ),
    ]
