# Generated by Django 2.0.2 on 2018-09-28 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180928_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='amar',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 10, 37, 54, 455792)),
        ),
    ]
