# Generated by Django 2.0.2 on 2018-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_amar_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amar',
            name='date1',
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='mahsoolName',
            field=models.CharField(max_length=100, verbose_name='نام کالا'),
        ),
    ]
