# Generated by Django 2.0.2 on 2018-09-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180930_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedehkar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ بدهکاری')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bedehkar',
            },
        ),
        migrations.CreateModel(
            name='BedehkarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedehkarName', models.CharField(max_length=100, verbose_name='نام بدهکاری')),
            ],
            options={
                'db_table': 'bedehkartype',
            },
        ),
        migrations.CreateModel(
            name='Talab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ بدهکاری')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('talabName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.BedehkarType')),
            ],
            options={
                'db_table': 'talab',
            },
        ),
        migrations.CreateModel(
            name='TalabType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedehkarType', models.CharField(max_length=100, verbose_name='نام بدهکاری')),
            ],
            options={
                'db_table': 'talabtype',
            },
        ),
        migrations.AddField(
            model_name='bedehkar',
            name='bedehKarName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.BedehkarType'),
        ),
    ]
