# Generated by Django 2.0.2 on 2018-09-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181001_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talabtype',
            old_name='bedehkarType',
            new_name='talabType',
        ),
        migrations.AlterField(
            model_name='talab',
            name='talabName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TalabType'),
        ),
    ]
