# Generated by Django 2.0.2 on 2018-09-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181001_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talabtype',
            old_name='talabType',
            new_name='talabName',
        ),
    ]
