# Generated by Django 2.0.2 on 2018-10-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20181001_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meghdar', models.FloatField(blank=True, default=0, null=True, verbose_name='میلغ')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hazine',
            },
        ),
        migrations.CreateModel(
            name='HazineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazineName', models.CharField(max_length=100, verbose_name='نام هزینه')),
            ],
            options={
                'db_table': 'hazinetype',
            },
        ),
        migrations.AlterField(
            model_name='bedehkar',
            name='bedehKarName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.BedehkarType', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='talab',
            name='talabName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TalabType', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='talabtype',
            name='talabName',
            field=models.CharField(max_length=100, verbose_name='نام طلب'),
        ),
        migrations.AddField(
            model_name='hazine',
            name='hazineName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TalabType', verbose_name='نوع'),
        ),
    ]
