# Generated by Django 2.0.2 on 2018-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20181002_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsool',
            name='mType',
            field=models.IntegerField(choices=[(0, 'نخ'), (1, 'الیاف'), (2, 'ضایعات')], default=1, verbose_name='نوع کالا'),
            preserve_default=False,
        ),
    ]
