# Generated by Django 2.0.2 on 2018-10-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181018_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazine',
            name='timestamp',
            field=models.DateField(blank=True),
        ),
    ]
